version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db_new
    environment:
      POSTGRES_DB: Manage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456789"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_pg_new
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: "pepa-linha"
      
volumes:
  postgres_data:
